add create_reference method
thoth-pub/thoth-client pull request #18
Opened 2023-01-10 16:27 UTC by lb803

Add method to add references to works.

2023-01-11 09:07 UTC, ja573 requested changes
Since references were introduced in v0.9.0, I'll set up a new version dir in the client before merging

2023-01-11 11:10 UTC, ja573 commented
> Since references were introduced in v0.9.0, I'll set up a new version dir in the client before merging

I've just merged #19 which adds the `thothlibrary/thoth-0_9_0` dir

2023-01-11 12:11 UTC, lb803 commented
OK, perfect! This should do!

2023-01-12 09:22 UTC, ja573 approved these changes

2023-01-12 09:23 UTC, merged